package jk.bd.app.common

object IngestConstants {

  val SRC_DB_NAME = "SRC_DB_NAME"
  val SRC_TABLE_NAMES_CSV = "SRC_TABLE_NAMES_CSV"
  val SRC_TABLE_NAME = "SRC_TABLE_NAME"

  val DEST_DB_NAME = "DEST_DB_NAME"
  val DEST_TABLE_NAMES_CSV = "DEST_TABLE_NAMES_CSV"
  val DEST_TABLE_NAME = "DEST_TABLE_NAME"
  val DEST_BASE_PATH = "DEST_BASE_PATH"

  val INGEST_CMD = "INGEST_CMD"
  val INGEST_CMD_SUFFIX = "INGEST_CMD_SUFFIX"

  val INGEST_DATE_YYYY = "INGEST_DATE_YYYY"
  val INGEST_DATE_MONTH = "INGEST_DATE_MONTH"
  val INGEST_DATE_DD = "INGEST_DATE_DD"
  val INGEST_DATE_HH = "INGEST_DATE_HH"
  val INGEST_DATE_MM = "INGEST_DATE_MM"
  val INGEST_DATE_SS = "INGEST_DATE_SS"

  val INGEST_ONE_TIME_ONLY = "INGEST_ONE_TIME_ONLY"
  val INGEST_ALL_DATA = "INGEST_ALL_DATA"

  val INGEST_BUSINES_DATE_START = "INGEST_BUSINES_DATE_START"
  val INGEST_BUSINES_DATE_END = "INGEST_BUSINES_DATE_END"

}