#!/bin/sh

INGEST_USER_CONFIG_FILE="${1}"
GLOBAL_CONFIG_FILE="${1}"

"$JAVA_CMD_PATH" -cp "$APP_LIB_PATH/*:$APP_CONFIG_PATH" jk.bd.app.ingest.Src2LndCLI "${INGEST_USER_CONFIG_FILE}"  "${GLOBAL_CONFIG_FILE}"